title            : "All The Language"
description      : >-
  Welcome! I'm <span class="tooltip" title="/wÉ›n/">Wen</span>.
  I study natural language, programming languages and logical languages.
  Basically, all the language...
url              : 'https://wenkokke.github.io'
baseurl          : ''
google_analytics : 'UA-74596735-1'
disqus_shortname : 'wenkokke'

author:
  name              : 'Wen Kokke'
  github_username   : wenkokke

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'


destination : _site
paginate    : 10
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
  math_engine: mathjax
highlighter : rouge

kramdown:
  input: GFM
  hard_wrap: false

gems    : ['jekyll-paginate']
include : 
  - 'keybase.txt'
  - 'story/*.pdf'
exclude :
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Rakefile'
  - '*.lagda'
  - '*.agdai'
  - '*.lhs'
  - '*.hs'
  - '*.hi'
  - '*.o'
  - '*.cabal'
  - '*.sh'
  - 'stack.yaml'
