title            : "All The Language"
description      : >-
  Welcome! I'm <span class="tooltip" title="/wÉ›n/">Wen</span>.
  I study natural language, programming languages and logical languages.
  Basically, all the language...
url              : 'https://wenkokke.github.io'
baseurl          : ''
google_analytics : 'UA-74596735-1'

author:
  name              : 'Wen Kokke'
  email             : wen.kokke@ed.ac.uk
  github_username   : wenkokke
  twitter_username  : wenkokke

defaults:
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

sass:
    sass_dir : _sass
    style: compressed

destination : _site
paginate    : 10
permalink   : /:year/:title/
markdown    : kramdown

include : 
  - 'keybase.txt'
  - 'story/*.pdf'
exclude :
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Makefile'
  - 'LICENSE'
  - '.travis.yml'
  - 'stack.yaml'
  - 'misc/'
  - 'src/'
  - '*.lagda'
  - '*.agdai'
  - '*.lhs'
  - '*.hs'
  - '*.hi'
  - '*.o'
  - '*.cabal'
  - '*.sh'
